server:
  port: 8081

logging:
  level:
    org.springframework: DEBUG
    co.spa.projectmanagement: DEBUG

jwt:
  secret: GEvjAbIMrYSg0bKzc9puQ2YiHTKby5fd7dAPhyvA/7pVFxgSEWnTU2JYy7diNsJVrXt0OWM2483IsJOnjC4XkA==

spring:
  application:
    name: project-management

  jackson:
    # Activar características para manejar JSON de forma flexible
    features:
      # Permite los comentarios en el JSON
      ALLOW_COMMENTS: true
      # Permite números con punto decimal al inicio (Ejemplo: .123)
      ALLOW_LEADING_DECIMAL_POINT_FOR_NUMBERS: true
      # Permite valores numéricos no definidos
      ALLOW_NON_NUMERIC_NUMBERS: true
      # Permite comas al final de los arrays/objetos JSON
      ALLOW_TRAILING_COMMA: true
      # Permite valores faltantes
      ALLOW_MISSING_VALUES: true
      # Permite caracteres especiales no escapados
      ALLOW_UNQUOTED_CONTROL_CHARS: true
      # Permite el uso de comillas simples en lugar de dobles
      ALLOW_SINGLE_QUOTES: true

  datasource:
    # URL de conexión a la base de datos PostgreSQL.
    # Usa una variable de entorno SPRING_DATASOURCE_URL si está definida; de lo contrario, se conecta a localhost:5432/control_proyectos.
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/projectdb}

    # Nombre de usuario de la base de datos.
    # Usa la variable de entorno SPRING_DATASOURCE_USERNAME si existe, o 'admin' por defecto.
    username: ${SPRING_DATASOURCE_USERNAME:admin}

    # Contraseña del usuario para acceder a la base de datos.
    # Usa la variable de entorno SPRING_DATASOURCE_PASSWORD si existe, o 'admin123' por defecto.
    password: ${SPRING_DATASOURCE_PASSWORD:admin123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  metrics:
    export:
      prometheus:
        enabled: true